cask_args appdir: '/Applications'

tap 'homebrew/versions'
tap 'caskroom/cask'
tap 'homebrew/dupes'

brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'autojump'
brew 'wget'
brew 'grep'
brew 'nmap'
brew 'htop'
brew 'tree'
brew 'rename'
brew 'git'
brew 'git-lfs'
brew 'git-flow'
brew 'git-extras'
brew 'stormssh'

brew 'python'
brew 'ruby'
brew 'node'
brew 'awscli'
brew 'kubernetes-cli'
brew 'kops'
brew 'terraform'
brew 'packer'
brew 'yarn'
brew 'flow'

cask 'google-chrome'
cask 'firefox'
cask 'iterm2'
cask 'sublime-text'
cask 'atom'
cask 'visual-studio-code'
cask 'virtualbox'
cask 'vagrant'
cask 'sourcetree'
cask 'spectacle'
cask 'flux'
cask 'screenhero'
cask 'robomongo'
cask 'postman'